
server:
  port: 8081
# DataSource Config
##配置加载的配置文件名的后缀
#spring:
#  profiles:
#    active: dev


spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  aop:
    proxy-target-class: true


  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  datasource:
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: jdbc:mysql://192.168.2.173:3306/face_detect?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    #    username: root
    #    password: mxjk0080
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: Zbx1314520!
  #########
  redis:
    host: localhost
    port: 6379
    timeout: 5000
  #  redis:
  #    host: 192.168.2.173
  #    port: 6379
  #    timeout: 5000
  # flyway 配置
  flyway:
    # 启用或禁用 flyway
    enabled: false
    # flyway 的 clean 命令会删除指定 schema 下的所有 table, 生产务必禁掉。这个默认值是 false 理论上作为默认配置是不科学的。
    clean-disabled: true
    # SQL 脚本的目录,多个路径使用逗号分隔 默认值 classpath:db/migration
    locations: classpath:db/migration
    #  metadata 版本控制信息表 默认 flyway_schema_history
    table: flyway_schema_history
    # 如果没有 flyway_schema_history 这个 metadata 表， 在执行 flyway migrate 命令之前, 必须先执行 flyway baseline 命令
    # 设置为 true 后 flyway 将在需要 baseline 的时候, 自动执行一次 baseline。
    baseline-on-migrate: true
    # 指定 baseline 的版本号,默认值为 1, 低于该版本号的 SQL 文件, migrate 时会被忽略
    baseline-version: 1
    # 字符编码 默认 UTF-8
    encoding: UTF-8
    # 是否允许不按顺序迁移 开发建议 true  生产建议 false
    out-of-order: false
    # 需要 flyway 管控的 schema list,这里我们配置为flyway  缺省的话, 使用spring.datasource.url 配置的那个 schema,
    # 可以指定多个schema, 但仅会在第一个schema下建立 metadata 表, 也仅在第一个schema应用migration sql 脚本.
    # 但flyway Clean 命令会依次在这些schema下都执行一遍. 所以 确保生产 spring.flyway.clean-disabled 为 true
    schemas: wisepark
    # 执行迁移时是否自动调用验证   当你的 版本不符合逻辑 比如 你先执行了 DML 而没有 对应的DDL 会抛出异常
    validate-on-migrate: true
  mail:

    # 负责发送验证码的邮箱
    email: zbx18967108248@163.com
    host: smtp.163.com
    port: 465
    username: zbx18967108248@163.com
    # 授权码是用于登录第三方邮件客户端的专用密码。
    password: TITCWRURSCQGHRLN
    default-encoding: UTF-8



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


logging:
  level:
    com:
      mxjk:
      smartpark: info


smartpark:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 172800
    header: Authorization

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379


code:
  expiration: 300
  #邮箱验证码有效时间/秒
#com:
#  mxjk:
#    snowflake:
#      machine-id: 1
#      data-center-id: 1
#
#accessFile:
#  resourceHandler: /show/** #匹配需要拦截的URL
#  location: /Users/zhangdada/Java/mxjk/sp-web/src/main/resources/static/  #本地文件夹
#
#files:
#  upload:
#    path: /Users/zhangdada/Java/mxjk/sp-web/src/main/resources/static/ #存放文件的自定义路径